#!/bin/zsh

SCRIPT=`basename $0`

source Docker/common/args.sh

function usage()
{
	printf "\n"
	printf "SYNOPSIS:\n"
	printf "\t${SCRIPT} --image --version --config\n\n"
	printf "SUMMARY:\n"
	printf "\tCreate ESP Logviewer docker image.\n"
	printf "\n"
	printf "OPTIONS:\n\n"
	printf "\t--image\t\timage name\n"
	printf "\t--version\timage version, defaults to v1.0\n"
	printf "\t--config\tKubernetes configuration file\n"
	printf "\n"
	exit 1
}

IMAGE=$parms[image]
VERSION=$parms[version]
CONFIG=$parms[config]

if [ -z "${IMAGE}" -o -z "${CONFIG}" ]
then
    usage
    exit 1
fi

if [ -z "${VERSION}" ]
then
    VERSION=v1.0
fi

cp ${CONFIG} Docker/common/config
docker build -t ${IMAGE}:${VERSION} --force-rm -f Docker/logviewer/k8s/Dockerfile .
rm Docker/common/config
