#!/bin/zsh

SCRIPT=`basename $0`

source Docker/common/args.sh

function usage()
{
	printf "\n"
	printf "SYNOPSIS:\n"
	printf "\t${SCRIPT} --image --config\n\n"
	printf "SUMMARY:\n"
	printf "\tCreate esp-connect docker image."
	printf "\n"
	printf "OPTIONS:\n\n"
	printf "\t--image\t\timage name\n"
	printf "\t--config\tKubernetes configuration file\n"
	printf "\n"
	exit 1
}

IMAGE=$parms[image]
CONFIG=$parms[config]

if [ -z "${IMAGE}" -o -z "${CONFIG}" ]
then
    usage
    exit 1
fi

cp ${CONFIG} Docker/common/config
docker build -t ${IMAGE} --force-rm -f Docker/connect/k8s/Dockerfile .
rm Docker/common/config
