#!/bin/zsh

SCRIPT=`basename $0`

source Docker/common/args.sh

function usage()
{
	printf "\n"
	printf "SYNOPSIS:\n"
    printf "\t${SCRIPT} --image --version\n\n"
	printf "SUMMARY:\n"
	printf "\tCreate ESP Modelviewer docker image.\n"
	printf "\n"
	printf "OPTIONS:\n\n"
	printf "\t--image\t\timage name\n"
	printf "\t--version\timage version, defaults to v1.0\n"
	printf "\n"
	exit 1
}

IMAGE=$parms[image]
VERSION=$parms[version]

if [ -z "${IMAGE}" ]
then
    usage $1
    exit 1
fi

if [ -z "${VERSION}" ]
then
    VERSION=v1.0
fi

docker build -t ${IMAGE}:${VERSION} --force-rm -f Docker/modelviewer/server/Dockerfile .
