#!/bin/zsh

SCRIPT=`basename $0`

source Docker/common/args.sh

function usage()
{
	printf "\n"
	printf "SYNOPSIS:\n"
    printf "\t${SCRIPT} --image\n\n"
	printf "SUMMARY:\n"
	printf "\tCreate ESP Modelviewer docker image.\n"
	printf "\n"
	printf "OPTIONS:\n\n"
	printf "\t--image\timage name\n"
	printf "\n"
	exit 1
}

IMAGE=$parms[image]

if [ -z "${IMAGE}" ]
then
    usage $1
    exit 1
fi

docker build -t ${IMAGE} --force-rm -f Docker/modelviewer/server/Dockerfile .
