apiVersion: iot.sas.com/v1alpha1
kind: ESPServer
metadata:
  name: simple # give the service used to access the running project a name
  #     ingress is <name>.<namespace>.$ESP_DOMAIN
  namespace: roleve
spec:
  # Add fields here
  failover: false
  loadBalancePolicy: "default" # in the future, we could add cluster-manager hash/round-robin...
  # if model has prefix "b64", treat it as based64 encoded 
  model: ""
  espProperties:
    server.xml: "b64PD94bWwgdmVyc2lvbj0iMS4wIj8+Cjxwcm9qZWN0IG5hbWU9InNpbXBsZSIgcHVic3ViPSJhdXRvIiB0aHJlYWRzPSI0Ij4KICAgIDxjb250cXVlcmllcz4KICAgICAgICA8Y29udHF1ZXJ5IG5hbWU9ImNxIiB0cmFjZT0icyI+CiAgICAgICAgICAgIDx3aW5kb3dzPgogICAgICAgICAgICAgICAgPHdpbmRvdy1zb3VyY2UgbmFtZT0icyI+CiAgICAgICAgICAgICAgICAgICAgPHNjaGVtYT4KICAgICAgICAgICAgICAgICAgICAgICAgPGZpZWxkcz4KICAgICAgICAgICAgICAgICAgICAgICAgPGZpZWxkIG5hbWU9ImlkIiB0eXBlPSJzdHJpbmciIGtleT0idHJ1ZSIvPgogICAgICAgICAgICAgICAgICAgICAgICA8ZmllbGQgbmFtZT0ic3RyIiB0eXBlPSJzdHJpbmciLz4KICAgICAgICAgICAgICAgICAgICAgICAgPGZpZWxkIG5hbWU9Im51bSIgdHlwZT0iaW50MzIiLz4KICAgICAgICAgICAgICAgICAgICAgICAgPC9maWVsZHM+CiAgICAgICAgICAgICAgICAgICAgPC9zY2hlbWE+CiAgICAgICAgICAgICAgICA8L3dpbmRvdy1zb3VyY2U+CiAgICAgICAgICAgIDwvd2luZG93cz4KICAgICAgICA8L2NvbnRxdWVyeT4KICAgIDwvY29udHF1ZXJpZXM+CjwvcHJvamVjdD4K"
  name: simple
  projectTemplate: # deployment template for the project, overridden by ESPServer; ((...)) means a placeholder for the operator to fill in, ports 31415 and 31416 will be replaced if the project is configured to use different ports.
    autoscale:
      minReplicas: 1
      maxReplicas: 1
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
    deployment:
      apiVersion: ""
      kind: ESPTemplate
      spec:
        selector:
          matchLabels:
        template: # required
          spec: # required
            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: esp-pv
            containers:
              - name: ((PROJECT_SERVICE_NAME)) # DONT CHANGE THE NAME
                resources:
                  requests:
                    memory: "1Gi"
                    cpu: "1"
                  limits:
                    memory: "2Gi"
                    cpu: "2"
                volumeMounts:
                  - mountPath: /mnt/data # path persistent volume gets mounted to
                    name: data # the volume specified below
                    #                   subPath: roleve
  loadBalancerTemplate: # deployment template for the project, overridden by ESPServer; ((...)) means a placeholder for the operator to fill in, ports 31415 and 31416 will be replaced if the project is configured to use different ports.
    deployment:
      apiVersion: ""
      kind: ESPTemplate
      spec: # required for deployment spec
        template: # required
          spec: # required
            containers:
              - name: ((PROJECT_SERVICE_NAME))
